// Ready-made boards. Clues is the default Misclickers paste-from-Discord style:
// mix of countable WOM clue tiles and screenshot tiles (pets, boots, 3rd age).

const { inferFromLabel } = require('./bingoParser');

function T(label) {
  const inferred = inferFromLabel(label);
  return { label, verify_mode: inferred.verify_mode, metric: inferred.metric, amount: inferred.amount || 0 };
}

const TEMPLATES = {
  clues: {
    name: 'Clues',
    hint: 'Standard 5×5 clue board',
    tiles: [
      T('5 hard clues'),
      T('Clue pet drop'),
      T('3rd age drop'),
      T('Hard clue screenshot'),
      T('10 easy clues'),
      T('Master clue stash fill'),
      T('Beginner clue casket'),
      T('10 medium clues'),
      T('3 elite clues'),
      T('Ranger boots'),
      T('Uri emote clue'),
      T('Holy sandals'),
      T('15 clues any tier'),
      T('1 master clue'),
      T('Wizard boots'),
      T('Gilded item'),
      T('Easy clue screenshot'),
      T('Medium clue screenshot'),
      T('Elite clue screenshot'),
      T('Master clue screenshot'),
      T('5 beginner clues'),
      T('Sherlock step'),
      T('Falo the Bard step'),
      T('Any god page'),
      T('Clue casket in the wildy'),
    ],
  },
  'clues-hardcore': {
    name: 'Clues — hardcore',
    hint: 'Masters, 3rd age, and stingy counts',
    tiles: [
      T('3 master clues'),
      T('5 elite clues'),
      T('10 hard clues'),
      T('Clue pet drop'),
      T('3rd age drop'),
      T('Gilded item'),
      T('Ranger boots'),
      T('Wizard boots'),
      T('Holy sandals'),
      T('Master clue stash fill'),
      T('Uri emote clue'),
      T('Sherlock step'),
      T('Falo the Bard step'),
      T('Any god page'),
      T('Blessed dhide drop'),
      T('25 clues any tier'),
      T('Hard clue screenshot'),
      T('Elite clue screenshot'),
      T('Master clue screenshot'),
      T('Clue casket in the wildy'),
      T('Beginner clue casket'),
      T('10 medium clues'),
      T('10 easy clues'),
      T('3rd age screenshot'),
      T('Any rare from a master'),
    ],
  },
  'boots-and-pets': {
    name: 'Boots and pets',
    hint: 'Screenshot-heavy flex board',
    tiles: [
      T('Ranger boots'),
      T('Wizard boots'),
      T('Holy sandals'),
      T('Clue pet drop'),
      T('Any skilling pet'),
      T('Any boss pet'),
      T('Heron'),
      T('Beaver'),
      T('Rock golem'),
      T('Giant squirrel'),
      T('Tangleroot'),
      T('Rift guardian'),
      T('Baby chinchompa'),
      T('Chompy chick'),
      T('3rd age drop'),
      T('Gilded item'),
      T('1 master clue'),
      T('5 hard clues'),
      T('3 elite clues'),
      T('Uri emote clue'),
      T('Master clue stash fill'),
      T('Any god page'),
      T('Hard clue screenshot'),
      T('Elite clue screenshot'),
      T('Master clue screenshot'),
    ],
  },
  'pvm-lite': {
    name: 'PvM lite',
    hint: 'Low-bar KC tiles plus a few flex screenshots',
    tiles: [
      { label: '25 Zulrah', verify_mode: 'wom_kc', metric: 'zulrah', amount: 25 },
      { label: '25 Vorkath', verify_mode: 'wom_kc', metric: 'vorkath', amount: 25 },
      { label: '25 Hydra', verify_mode: 'wom_kc', metric: 'alchemical_hydra', amount: 25 },
      { label: '50 Kraken', verify_mode: 'wom_kc', metric: 'kraken', amount: 50 },
      { label: '10 Muspah', verify_mode: 'wom_kc', metric: 'phantom_muspah', amount: 10 },
      { label: '10 Corp', verify_mode: 'wom_kc', metric: 'corporeal_beast', amount: 10 },
      { label: '10 Bandos', verify_mode: 'wom_kc', metric: 'general_graardor', amount: 10 },
      { label: '10 Zilyana', verify_mode: 'wom_kc', metric: 'commander_zilyana', amount: 10 },
      { label: '5 CoX', verify_mode: 'wom_kc', metric: 'chambers_of_xeric', amount: 5 },
      { label: '5 ToA', verify_mode: 'wom_kc', metric: 'tombs_of_amascut', amount: 5 },
      { label: '1 Jad', verify_mode: 'wom_kc', metric: 'tztok_jad', amount: 1 },
      { label: '10 Gauntlet', verify_mode: 'wom_kc', metric: 'the_gauntlet', amount: 10 },
      { label: '10 Duke', verify_mode: 'wom_kc', metric: 'duke_sucellus', amount: 10 },
      { label: '10 Leviathan', verify_mode: 'wom_kc', metric: 'the_leviathan', amount: 10 },
      { label: '10 Whisperer', verify_mode: 'wom_kc', metric: 'the_whisperer', amount: 10 },
      { label: '10 Vardorvis', verify_mode: 'wom_kc', metric: 'vardorvis', amount: 10 },
      T('Any boss pet'),
      T('Any unique screenshot'),
      { label: '25 Giant Mole', verify_mode: 'wom_kc', metric: 'giant_mole', amount: 25 },
      { label: '10 KQ', verify_mode: 'wom_kc', metric: 'kalphite_queen', amount: 10 },
      { label: '3 ToB', verify_mode: 'wom_kc', metric: 'theatre_of_blood', amount: 3 },
      { label: '5 Nex', verify_mode: 'wom_kc', metric: 'nex', amount: 5 },
      { label: '25 Cerberus', verify_mode: 'wom_kc', metric: 'cerberus', amount: 25 },
      T('Purple screenshot'),
      T('Deathless raid screenshot'),
    ],
  },
  'mixed-casual': {
    name: 'Mixed casual',
    hint: 'Clues + light PvM + skilling, good for a lazy week',
    tiles: [
      T('5 hard clues'),
      T('10 easy clues'),
      T('10 medium clues'),
      T('Ranger boots'),
      T('Clue pet drop'),
      { label: '25 Zulrah', verify_mode: 'wom_kc', metric: 'zulrah', amount: 25 },
      { label: '25 Vorkath', verify_mode: 'wom_kc', metric: 'vorkath', amount: 25 },
      { label: '50 Wintertodt', verify_mode: 'wom_kc', metric: 'wintertodt', amount: 50 },
      { label: '50 Tempoross', verify_mode: 'wom_kc', metric: 'tempoross', amount: 50 },
      { label: '100k Agility XP', verify_mode: 'wom_xp', metric: 'agility', amount: 100000 },
      { label: '100k Slayer XP', verify_mode: 'wom_xp', metric: 'slayer', amount: 100000 },
      T('1 master clue'),
      T('3 elite clues'),
      T('Uri emote clue'),
      T('Any skilling pet'),
      T('Hard clue screenshot'),
      { label: '25 Giant Mole', verify_mode: 'wom_kc', metric: 'giant_mole', amount: 25 },
      { label: '10 Gauntlet', verify_mode: 'wom_kc', metric: 'the_gauntlet', amount: 10 },
      T('Beginner clue casket'),
      T('15 clues any tier'),
      T('Wizard boots'),
      T('Holy sandals'),
      T('Any boss pet'),
      { label: '100k Fishing XP', verify_mode: 'wom_xp', metric: 'fishing', amount: 100000 },
      T('Complete a quest'),
    ],
  },
};

function templateKeys() {
  return Object.keys(TEMPLATES);
}

function getTemplate(key) {
  return TEMPLATES[key] || null;
}

module.exports = { TEMPLATES, templateKeys, getTemplate };
